package com.smmpanel.entity;

public enum AuditAction {
    // User actions
    USER_CREATED, USER_DELETED, USER_ROLE_CHANGED, USER_STATUS_CHANGED,
    API_KEY_GENERATED, API_KEY_REVOKED,
    // Order actions
    ORDER_CREATED, ORDER_STATUS_CHANGED, ORDER_COMPLETED, ORDER_CANCELLED,
    ORDER_PAUSED, ORDER_RESUMED, BULK_ORDER_OPERATION,
    // Binom actions
    BINOM_CAMPAIGN_CREATED, BINOM_CAMPAIGN_STOPPED, BINOM_CAMPAIGN_PAUSED, BINOM_CAMPAIGN_RESUMED,
    // Security actions
    USER_LOGIN_SUCCESS, USER_LOGIN_FAILED, USER_ACCOUNT_LOCKED, UNAUTHORIZED_ACCESS_ATTEMPT,
    // System actions
    SYSTEM_BACKUP, SYSTEM_RESTORE, CONFIGURATION_CHANGED
} 