groups:
- name: kafka_consumer_alerts
  rules:
  - alert: KafkaConsumerLagHigh
    expr: kafka_consumer_lag > 10000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High Kafka consumer lag"
      description: "Consumer group {{ $labels.group }} has a lag of {{ $value }} messages"

  - alert: KafkaConsumerErrorRateHigh
    expr: rate(kafka_consumer_errors_total[5m]) / rate(kafka_consumer_processing_seconds_count[5m]) > 0.05
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate in Kafka consumer"
      description: "Consumer group {{ $labels.group }} has error rate of {{ $value | humanizePercentage }}"

  - alert: KafkaConsumerDown
    expr: kafka_consumer_health == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Kafka consumer is down"
      description: "Consumer group {{ $labels.group }} is not healthy"

  - alert: KafkaConsumerProcessingSlowdown
    expr: rate(kafka_consumer_processing_seconds_count[5m]) < 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kafka consumer processing slowdown"
      description: "Consumer group {{ $labels.group }} is processing messages too slowly"

  - alert: KafkaConsumerPartitionRebalancing
    expr: changes(kafka_consumer_assigned_partitions[5m]) > 0
    labels:
      severity: info
    annotations:
      summary: "Kafka consumer partition rebalancing"
      description: "Consumer group {{ $labels.group }} is rebalancing partitions"
