package com.smmpanel.dto.instagram;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Message format for Instagram orders sent via RabbitMQ. This matches the format expected by the
 * Instagram bot.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InstagramOrderMessage {

    /** Unique order ID generated by the bot */
    private String id;

    /** Panel's order ID for correlation */
    @JsonProperty("external_id")
    private String externalId;

    /** Order type: like, comment, follow, like_follow, like_comment, like_comment_follow */
    private String type;

    /** Instagram URL to target */
    @JsonProperty("target_url")
    private String targetUrl;

    /** Number of actions to perform */
    private int count;

    /** Optional comment text for comment orders */
    @JsonProperty("comment_text")
    private String commentText;

    /** Webhook URL for result notifications */
    @JsonProperty("callback_url")
    private String callbackUrl;

    /** Order priority (0-9, higher = more important) */
    @Builder.Default private int priority = 0;

    /** Order creation timestamp */
    @JsonProperty("created_at")
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Retry count for failed orders */
    @JsonProperty("retry_count")
    @Builder.Default
    private int retryCount = 0;

    /** Maximum retry attempts */
    @JsonProperty("max_retries")
    @Builder.Default
    private int maxRetries = 3;
}
