# Kafka Error Handling Configuration
app:
  kafka:
    error-handling:
      # Retry configuration
      max-retries: 5
      initial-interval: 1000        # 1 second
      max-interval: 30000          # 30 seconds  
      multiplier: 2.0              # Exponential backoff multiplier
      use-exponential-backoff: true
      
      # Error metadata configuration
      include-stack-trace: false   # Set to true in development
      
      # Topic-specific configurations with business rationale
      topics:
        order-processing:
          max-retries: 3            # Orders need fast processing, limited retries
          initial-interval: 2000    # Quick first retry for transient issues
          max-interval: 60000       # Max 1 minute delay for order processing
          include-stack-trace: true # Debug order issues quickly
        
        video-processing:
          max-retries: 5            # Video processing can handle more retries
          initial-interval: 5000    # Longer initial wait for heavy processing
          max-interval: 300000      # 5 minutes - video processing is not time-critical
          
        youtube-processing:
          max-retries: 10           # YouTube API can be flaky, need patience
          initial-interval: 10000   # Start with 10s due to API rate limits
          max-interval: 600000      # 10 minutes max - respect YouTube quotas
          
        high-priority:
          max-retries: 7            # Critical business operations
          initial-interval: 500     # Very fast retry for urgent tasks
          max-interval: 10000       # Max 10s delay for high priority items
          
        dlq-processing:
          max-retries: 2            # DLQ items already failed multiple times
          initial-interval: 5000    # Slower processing for problem messages
          max-interval: 10000       # Limited retry for DLQ recovery
    
    # Dead Letter Queue configuration
    dlq:
      enabled: true
      retention-days: 30
      max-message-size: 1048576    # 1 MB
      compression: snappy
      
      # DLQ processing configuration
      processing:
        enabled: true
        batch-size: 100
        poll-interval: 30000       # 30 seconds
        max-processing-time: 300000 # 5 minutes
        
      # DLQ cleanup configuration  
      cleanup:
        enabled: true
        schedule: "0 2 * * *"      # Daily at 2 AM
        retention-days: 30
        
    # Error monitoring and alerting
    monitoring:
      enabled: true
      error-threshold: 10          # Alert after 10 errors per minute
      dlq-threshold: 5             # Alert after 5 DLQ messages per minute
      alert-channels:
        - slack
        - email
        - metrics
        
      # Metrics collection
      metrics:
        enabled: true
        collection-interval: 60000  # 1 minute
        retention-hours: 24
        
# Spring Kafka overrides for error handling
spring:
  kafka:
    consumer:
      properties:
        # Consumer error handling
        max.poll.interval.ms: 300000
        session.timeout.ms: 30000
        heartbeat.interval.ms: 3000
        
        # Error resilience
        retry.backoff.ms: 100
        reconnect.backoff.ms: 50
        reconnect.backoff.max.ms: 1000
        
        # Memory and performance
        fetch.max.bytes: 52428800    # 50 MB
        max.partition.fetch.bytes: 1048576 # 1 MB
        
    producer:
      properties:
        # Producer error handling for DLQ
        retry.backoff.ms: 100
        reconnect.backoff.ms: 50
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
        
# Logging configuration for Kafka error handling
logging:
  level:
    com.smmpanel.config.KafkaConsumerErrorConfiguration: INFO
    com.smmpanel.service.DeadLetterQueueService: INFO
    org.springframework.kafka.listener.DefaultErrorHandler: WARN
    org.springframework.kafka.listener.DeadLetterPublishingRecoverer: INFO
    
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    
# Management endpoints for error monitoring  
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,kafka-errors
  endpoint:
    kafka-errors:
      enabled: true
      
  metrics:
    tags:
      application: smm-panel
      environment: ${spring.profiles.active:default}
    export:
      prometheus:
        enabled: true