# Production Environment Configuration
# Optimized for performance with minimal logging and maximum throughput

spring:
  # ===============================
  # PRODUCTION LIQUIBASE CONFIGURATION
  # ===============================
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: prod
    drop-first: false  # CRITICAL: Never drop in production
    test-rollback-on-update: false
    # Minimal logging for production performance
    verbose: false
    rollback-file: /var/log/smm-panel/liquibase-rollback.sql

  # ===============================
  # PRODUCTION JPA/HIBERNATE CONFIG
  # ===============================
  jpa:
    # Disable SQL logging in production
    show-sql: false
    properties:
      hibernate:
        # Minimal SQL formatting
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
        
        # ===============================
        # PRODUCTION STATISTICS
        # ===============================
        generate_statistics: false
        
        # ===============================
        # OPTIMIZED BATCH CONFIGURATION
        # ===============================
        jdbc:
          batch_size: 100  # Maximum batch size for production
          batch_versioned_data: true
          fetch_size: 200  # Larger fetch size for production
          time_zone: UTC
          
        # ===============================
        # PRODUCTION QUERY OPTIMIZATION
        # ===============================
        default_batch_fetch_size: 64  # Maximum batch fetch for production
        max_fetch_depth: 3
        
        # ===============================
        # QUERY PLAN CACHING (PRODUCTION)
        # ===============================
        query:
          plan_cache_max_size: 8192  # Large cache for production
          plan_parameter_metadata_max_size: 512
          in_clause_parameter_padding: true
          
        # ===============================
        # SECOND LEVEL CACHE (PRODUCTION)
        # ===============================
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          default_cache_concurrency_strategy: read_write
          
        # ===============================
        # PRODUCTION OPTIMIZATIONS
        # ===============================
        temp:
          use_jdbc_metadata_defaults: false
        auto_quote_keyword: false
        globally_quoted_identifiers: false

# ===============================
# PRODUCTION LOGGING CONFIGURATION
# ===============================
logging:
  level:
    root: WARN
    com.smmpanel: INFO
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
    com.zaxxer.hikari: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ===============================
# PRODUCTION DATABASE CONFIGURATION
# ===============================
# ===============================
# PRODUCTION DATASOURCE OVERRIDES
# ===============================
spring:
  datasource:
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:200}    # Optimized for production load
      minimum-idle: ${DB_MIN_IDLE:20}               # Higher minimum for prod
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}  # Standard prod timeout
      max-lifetime: ${DB_MAX_LIFETIME:1800000}      # 30 minutes

app:

  # ===============================
  # PRODUCTION CACHE CONFIGURATION
  # ===============================
  cache:
    # Production cache TTL - longer for better performance
    services:
      ttl: ${CACHE_SERVICES_TTL:7200}      # 2 hours - stable in production
    users:
      ttl: ${CACHE_USERS_TTL:3600}         # 1 hour - balance freshness/performance
    conversion-coefficients:
      ttl: ${CACHE_COEFFICIENTS_TTL:14400}  # 4 hours - rarely change
    youtube-stats:
      ttl: ${CACHE_YOUTUBE_TTL:600}         # 10 minutes - regular updates needed

# ===============================
# PRODUCTION MONITORING
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: never
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60s
    enable:
      jvm: true
      process: true
      system: true
      hibernate: false  # Disable Hibernate metrics in production

# ===============================
# PRODUCTION PERFORMANCE TUNING
# ===============================
server:
  tomcat:
    # Production thread pool sizing
    threads:
      max: 400
      min-spare: 50
    # Production connection settings
    max-connections: 16384
    connection-timeout: PT10S
    keep-alive-timeout: PT10S